
jobs:
    include:
        - stage: "PHP lint tests"
          language: php
          sudo: required
          php:
            - 7.4
            - 8.0
          install:
            - curl -s http://getcomposer.org/installer | php
            - php composer.phar install --dev --no-interaction
          script:
            - php vendor/bin/phpcs -p src
            - php vendor/bin/phpstan analyse -c phpstan.neon -l max src
